### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Omicron166yt** [hassan-tahir/Faceboom#1]
File "facebom.py", line 281, in <module>
    Main()
  File "facebom.py", line 275, in Main
    ID(url)
  File "facebom.py", line 68, in ID
    idis = idre.findall(con)
TypeError: cannot use a string pattern on a bytes-like object

python version: 3.9.4
platform: termux no root arm64

**Comment by hassan-tahir** [comment]
Termux Environment not supported for this program, you can try it on linux env with python 2.7
